### PR TITLE
TR_localization Added For ElvUI\Core\Locales

### PR DESCRIPTION
**Pull request by mgedikli**
We're added "trTr.lua" for "ElvUI\Core\Locales"
"General.lua" updated for "Language Prefer List"
Turkish letters changed to universal form for temporarily.

### CODE REVIEW

**Comment by kodewdle** [comment]
hey, this is really cool thank you. would you be willing to also translate the one here: https://github.com/tukui-org/ElvUI/tree/development/ElvUI_OptionsUI/Locales

btw, you don't need to translate all, please see: https://github.com/tukui-org/ElvUI/commit/50902cd177aa687bbcf7749e43229a27b80a784e

thank you for the work you did do tho ! :)

**Comment by mgedikli** [comment]
> 

Thanks your kindly reply :) .We're working on it. Almost done 👍

**Comment by kodewdle** [comment]
ok great!  i have made the file already. here: https://github.com/tukui-org/ElvUI/blob/development/ElvUI_OptionsUI/Locales/trTR.lua

you will need to "reset" your option in profile from `trTr` to `trTR` otherwise you might get an error when opening the options!

**Comment by kodewdle** [comment]
to be clear in that file, some will have the same matching name, this is because our options don't use the game client information (so we can have language like turkish for example, even tho WoW does not!) so in that case, we need to have a matching name. like this one: `L["UNIT_NAMEPLATES_AUTOMODE"] = "Always Show Nameplates"` but this only applies for some. (mainly ones with caps lock key: `L["UNIT_NAMEPLATES_AUTOMODE"]`)

**Comment by kodewdle** [comment]
`L["PAIN"] = "Pain"` is another example, where it would normally use a global but we use a custom one so that other languages are supported :)

**Comment by mgedikli** [comment]
@kodewdle i got it, thanks for tips and informations :) . We're glad to learn that.

**Comment by mgedikli** [comment]
@kodewdle We are sorry to bother you, we're trying to see changes on "ElvUI\ElvUI_OptionsUI\Locales" but it's not working while in game. How could we import "trTR.lua" on this path into game?

**Pull request merged**
