### PR TITLE
Extend fader options

### PR DESCRIPTION
**Pull request by happenslol**
This PR extends the fader options to allow users to always show their player unitframe in different types of dungeons and raids.

I've taken care to only update the relevant value when the zone is actually changed, to avoid calling `GetInstanceInfo` too much. The options are only displayed for the player UnitFrame, and the IDs for different difficulties are taken from the WeakAuras `Load` options.

### CODE REVIEW

**Comment by kodewdle** [comment]
this is a really cool idea, thank you for the submitting! it would need a bit of adjustment here and there but the idea is cool. i will try to have a look at this before the next release and see if i can get something implemented from this! 🌼

**Comment by kodewdle** [comment]
let me know (discord can work too) if you have trouble with the hover now, i seen you might have mistakenly removed part of this code for handling hover for some things; that is required to function other parts but it only is meant when you send a table to the SetOptions, which we don't need for this, i made it send a boolean instead ;)

**Comment by kodewdle** [comment]
to be clear, this is in development branch now! :)

**Comment by kodewdle** [comment]
did some more work on it, have the cache properly handled as you toggle the option by cleaning it sooner and it will "refresh" when you use the option :)

**Comment by happenslol** [comment]
Awesome, thank you! Looking forward to not having to update my fork anymore :-P

**Comment by kodewdle** [comment]
of course! just hit me up if you have any issue with the changes i made ;) 🌼

**Comment by happenslol** [comment]
Looks all good to me. The refresh when toggling the option was working for me, but there probably were some edge cases I didn't consider. The code embedding the element/fader in each option table was a little hard to understand and I still don't really know what `count` does, so it's good you looked it over :-)

**Comment by kodewdle** [comment]
`count` is used to track how many options are in-use right now (so it can early break if none are currently used)

**Comment by kodewdle** [comment]
i was thinking, perhaps `SetOption` was the confusing part as we don't normally did this i did something *different* which can usually lead to confusion on what is happening; but by design i felt in this case since the events are toggled around it was better this way 😓

happy to help tho! thank you for your contribution 🌼

**Comment by kodewdle** [comment]
> but there probably were some edge cases I didn't consider

the edge case was with only the single option (so only checked for one type and nothing else, weird i know but it counts).  i had to find a way that it can work regardless of some options on or not (which wasn't the case, but is fine now)

**Comment by happenslol** [comment]
Ohhh that makes sense, totally overlooked the abort condition. Thanks for the explanation!

I think if more options are ever added, especially more complicated/interdependent ones, the whole thing could use more caching in a similar way to how the instance info is cached now. Feels to me like it would be way easier to do if the `Update` function actually receives the event name that triggers it. But that's for another time :-P

> the edge case was with only the single option (so only checked for one type and nothing else, weird i know but it counts). i had to find a way that it can work regardless of some options on or not (which wasn't the case, but is fine now)

Duh, I didn't think of that. Good catch!

**Comment by kodewdle** [comment]
i agree with your statement about the caching generally more can be better if it's not overly complicated a lot of these calls are already cached by the client itself- rather than in the lua.  so, you do call the API but the client actually returns a cached result (that isn't fetched from storage).  caching is quite useful tho, so thank you for considering performance.  we've been working on that when we can :)

**Pull request merged**
