### PR TITLE
add child list command for dev and fix tooltip show data option

### PR DESCRIPTION
**Pull request by fxpw**

### CODE REVIEW

**Comment by Repooc** [comment]
The tooltip isnt broken. We did that for a reason.  If that is something you want, you will have to do it in a plugin for yourself.  We are not going to add the child list either for a couple reason, u can use `/tinspect` and u are using loadstring which we dont feel the need for in the addon and if you are really wanting the ability, might as well make a dev addon for yourself with that in it.

**Comment by fxpw** [comment]
> The tooltip isnt broken. We did that for a reason and really rather not change it back even with an option. If that is something you want, you will have to do it in a plugin for yourself. We are not going to add the child list either for a couple reason, u can use `/tinspect` and u are using loadstring which we dont feel the need for in the addon and if you are really wanting the ability, might as well make a dev addon for yourself with that in it.

At the current moment, it only shows when the parameter is enabled and the key is pressed. I made the setting whether to show, whether to show when pressed and not to show if the display is not enabled. Is it possible to find out in more detail why you did not do it right away?

**Comment by kodewdle** [comment]
@fxpw  checking another players inspect info is throttled by the client, if we spam calls with mouseover addons that use it in raids (more important ones) will get blocked calls and fail to have the data they need for raid leaders

**Comment by fxpw** [comment]
> @fxpw checking another players inspect info is throttled by the client, if we spam calls with mouseover addons that use it in raids (more important ones) will get blocked calls and fail to have the data they need for raid leaders

Ty

**Pull request closed without merging**
