### PR TITLE
[Feature Request] Split Bar

### PR DESCRIPTION
**Pull request by dlecina**
**Is your feature request related to a problem? Please describe.**
I would like to be able to split bars into two segments, allowing for some element to sit in between them such as a minimap, player unit frame, etc. This can be seen in other MMOs such as GW2.

**Describe the solution you'd like**
An option to split a bar in two, providing which button to split from (usually, the middle of the bar) and how big the spacing should be.

**Describe alternatives you've considered**
Using different bars for each segment. This could be compared to the columns feature, which can also be done by setting up different bars. This alternative has the following disadvantages:
- Twice as much configuration
- Can't use normal WoW keybinds (bad when a new patch comes out and addons break)
- Can't benefit from default setup / must duplicate configuration regarding paging, Druid forms, etc.
- Can effectively only use half as many bars as the addon would normally allow
- Cannot be done for special bars (stance bar etc)

**Additional context**
I've provided a PR to add this feature, which I hope you will accept. I am ready and willing to make any changes necessary in case I missed some thing as I am not familiar with the codebase.
I tried doing this via Plugin but it's much easier and user-friendly to just contribute to the addon directly. Via Plugin, I would have to do some very ugly and hard to maintain hacks to add this feature.

### CODE REVIEW

**Comment by dlecina** [comment]
Here is a preview of the end result I am hoping to add. This is only 4 bars instead of 8:
image

**Comment by Repooc** [comment]
To be honest what you have done here can EASILY (at least it should be) done as a plugin by hooking AB:HandleButton basically.  If Simpy is willing to add the feature, you are missing locale entries (even if you dont have them translated) for the other languages and missing profile defaults for the new options.

**Comment by kodewdle** [comment]
> Here is a preview of the end result I am hoping to add. This is only 4 bars instead of 8: image

image

**Comment by Repooc** [comment]
or 
image

**Comment by Repooc** [comment]
After talking with simpy (still havent heard input from others), we prob won't merge this in... I could prob make a small plugin for this idea though if you want something like this (assuming my thought process is as easy as i said earlier)

**Comment by dlecina** [comment]
Your way of doing this in 4 bars is clever, but the behavior for shapeshifting etc. is still not quite what I'd like. I appreciate your comments, though.

Don't feel obliged to do the plugin yourself, I just need some pointers so I can do it myself because I am not very familiar with either the codebase or Lua as a language...

When I tried doing it as a plugin, I tried something like this:
```
local E, L, V, P, G = unpack(ElvUI)
local AB = E:GetModule('ActionBars')

local AB_HandleButton = AB.HandleButton
function CustomHandleButton(bar, button, index, lastButton, lastColumnButton)
    -- print('index error: ' .. index)
    AB_HandleButton(bar, button, index, lastButton, lastColumnButton)
end
AB.HandleButton = CustomHandleButton
```
Obviously, I would add some code either before or after the call to the original function, or replace it altogether. The problem I found is that in this case index did not have the value I expected, and indeed this print gave me an error. However, the original function was still being called via mine (I verified this but printing some constant), and the same print of index inside the function would work normally. I still don't understand this behavior.

Also can you tell me whether it is possible to add the options in the base Action Bars options UI like I did in this PR via plugin, or will I need to come up with something different and put it in my plugin's options?

Thank you for your time!

**Comment by Repooc** [comment]
To be honest, it was easier for me to whip something up instead of trying to do any explanations.  Here is the plugin for you to take for a test drive.
https://github.com/Repooc/ElvUI_SplitActionBars

**Pull request closed without merging**
