### PR TITLE
TBC nameplate threat color

### PR DESCRIPTION
**Pull request by phrdina**
Hi, I'm enjoying this awesome addon playing wow classic TBC but recently I started tanking as well and was missing this functionality from retail.

This will correctly set the player role to tank if in raid and the player is marked as main tank and it will correctly show threat colors of the enemy nameplates if offtank has aggro or other player manages to take the aggro.

### CODE REVIEW

**Comment by Azilroka** [comment]
You mean the code thats already in?

**Comment by Azilroka** [comment]
`function NP:ThreatIndicator_PreUpdate(unit, pass)
	local nameplate, db, unitTarget, imTank = self.__owner, NP.db.threat, unit..'target', E.myrole == 'TANK'
	local unitRole = NP.IsInGroup and (UnitExists(unitTarget) and not UnitIsUnit(unitTarget, 'player')) and NP.GroupRoles[UnitName(unitTarget)] or 'NONE'
	local unitTank = unitRole == 'TANK' or (db.beingTankedByPet and NP.ThreatPets[NP:UnitNPCID(unitTarget)])
	local isTank, offTank, feedbackUnit = unitTank or imTank, db.beingTankedByTank and (unitTank and imTank) or false, (unitTank and unitTarget) or 'player'

	nameplate.ThreatScale = nil

	if pass then
		return isTank, offTank, feedbackUnit
	else
		self.feedbackUnit = feedbackUnit
		self.offTank = offTank
		self.isTank = isTank
	end
end`

**Comment by Azilroka** [comment]
```
function NP:GROUP_ROSTER_UPDATE()
	local isInRaid = IsInRaid()
	NP.IsInGroup = isInRaid or IsInGroup()

	wipe(NP.GroupRoles)

	if NP.IsInGroup then
		local group = isInRaid and 'raid' or 'party'
		for i = 1, (isInRaid and GetNumGroupMembers()) or GetNumSubgroupMembers() do
			local unit = group .. i
			if UnitExists(unit) then
				NP.GroupRoles[UnitName(unit)] = not E.Retail and (GetPartyAssignment('MAINTANK', unit) and 'TANK' or 'NONE') or UnitGroupRolesAssigned(unit)
			end
		end
	end
end
```

**Comment by phrdina** [comment]
Hi :) well I did not properly update the development branch. At least my patches were not that different to yours :). Thanks a lot for that work!

**Pull request closed without merging**
