### PR TITLE
Update FR loc

### PR DESCRIPTION
**Pull request by Zazou49**

### CODE REVIEW

**Comment by kodewdle** [comment]
thanks, you dont need to translate all for example:  Boss -> Boss, can just stay as `true` but thank you!

**Comment by kodewdle** [comment]
https://github.com/tukui-org/ElvUI/commit/187019d771a475ced1c9badb237c1b87211926ee#comments this is for Instance shorthand, not like the "i" of "i did something" for example, it's shorthand letter for "instance"

**Comment by Zazou49** [comment]
> [187019d#r93248159](https://github.com/tukui-org/ElvUI/commit/187019d771a475ced1c9badb237c1b87211926ee#r93248159) this is for Instance shorthand, not like the "i" of "i did something" for example, it's shorthand letter for "instance"

Oh okay. I’m feeling dumb now 😅

**Comment by Zazou49** [comment]
> thanks, you dont need to translate all for example: Boss -> Boss, can just stay as `true` but thank you!

Alright ! Noted !

**Pull request merged**
