### PR TITLE
renown bar color

### PR DESCRIPTION
**Pull request by Kijascha**
set bar color to renown color when renown faction is being tracked

### CODE REVIEW

**Comment by Repooc** [comment]
Your pr doesn't do anything, u declared a var and is never set.

**Comment by Repooc** [comment]
That still isnt correct either.  You assigning the var `renownColor` on line 73 wont make a difference as it is still wrong. 
Basically doing the way you want, u are coloring the rep bar that blue no matter what the reputation is with the faction you are showing at this point.  If you want the bar blue, just go to the Databars section -> Color and enable the custom faction colors and change them all to the blue you want as that is basically what you are doing.

**Comment by Kijascha** [comment]
Sorry, but you are wrong in my opinion. My intention was to color only the renown bar in this respective color. And it works as intended. The other factions are not affected by this at all.

WoWScrnShot_102022_211016
WoWScrnShot_102022_211130
WoWScrnShot_102022_211138

**Comment by kodewdle** [comment]
done here: https://github.com/tukui-org/ElvUI/commit/8128666e90ee44b2b544dc463cba33d713cab527

**Comment by Repooc** [comment]
woot, thats more of a proper way lol

**Pull request closed without merging**
